tumor_data = load('tumor_example.txt','-ascii');
[change, rate,a,b,c,d] = tumorfit(tumor_data,5);
% figure;
% tumorplot(tumor_data,a,b,c,d);
[change_d,rate_d,a_d,b_d,c_d,d_d] = analyze_tumors('tumor_study/drug');
[change_p,rate_p,a_p,b_p,c_p,d_p] = analyze_tumors('tumor_study/placebo');
figure;
[X1,Y1] = cumhist(change_d);
[X2,Y2] = cumhist(change_p);
plot(X1,Y1);
hold on;
plot(X2,Y2);
% [change_d,rate_d,a_d,b_d,c_d,d_d]=analyze_tumors_plot('tumor_study/drug',1);
% [change_p,rate_p,a_p,b_p,c_p,d_p]=analyze_tumors_plot('tumor_study/placebo',1);